version: '3.8'
services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=docker_hospital_database
    networks:
      - local_network
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    ports:
      - "8080:80"
    networks:
      - local_network

  data_ingestion:
    build: .
    volumes:
      - ./data:/data
    depends_on:
      - postgres
    networks:
      - local_network

networks:
  local_network:

volumes:
  postgres_data:
